spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.consumer.properties.partition.assignment.strategy=org.apache.kafka.clients.consumer.CooperativeStickyAssignor
spring.kafka.streams.application-id=order-service-streams

spring.datasource.url=${DB_URL}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

management.endpoint.health.show-details=when-authorized
management.endpoint.health.roles=ACTUATOR_ADMIN
management.endpoints.web.exposure.include=health,prometheus

springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false

